# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=120)),
                ('Item_name', models.CharField(max_length=120)),
                ('item_picture', models.ImageField(upload_to='static/media')),
                ('Item_description', models.TextField(blank=True, help_text='Item Description', null=True)),
                ('Lost_place', models.CharField(max_length=120)),
                ('Date_Lost', models.DateTimeField(auto_now_add=True)),
                ('Value', models.IntegerField(null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-Updated', '-Timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=120)),
                ('First_name', models.CharField(max_length=120)),
                ('Course', models.CharField(max_length=120)),
                ('Year', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='itemlost',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.OwnerInfo'),
        ),
        migrations.AddField(
            model_name='itemlost',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
