# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlost',
            options={'ordering': ['-Updated', '-Time_lost']},
        ),
        migrations.RenameField(
            model_name='itemlost',
            old_name='Timestamp',
            new_name='Time_lost',
        ),
        migrations.AlterField(
            model_name='itemlost',
            name='Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso amount'),
        ),
    ]
