# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180113_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
