# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_itemlost_returned'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lost_place', models.CharField(max_length=120)),
                ('Date_Lost', models.DateField(default=datetime.date.today)),
                ('Time_lost', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itemlost',
            options={'ordering': ['-Updated', '-Time']},
        ),
        migrations.RenameField(
            model_name='itemlost',
            old_name='Date_Lost',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='itemlost',
            name='Lost_place',
        ),
        migrations.RemoveField(
            model_name='itemlost',
            name='Time_lost',
        ),
        migrations.AlterField(
            model_name='itemlost',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='Item'),
        ),
        migrations.AddField(
            model_name='itemlost',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.LocationLost'),
        ),
    ]
