# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180113_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_name', models.CharField(max_length=120)),
                ('First_name', models.CharField(max_length=120)),
                ('Course_or_Stran', models.CharField(max_length=120)),
                ('Year', models.CharField(max_length=90)),
            ],
        ),
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='Course',
            new_name='Course_or_Stran',
        ),
    ]
