# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-13 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180113_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlost',
            name='Returner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.ReturnerInfo'),
        ),
    ]
