# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_itemlost_returner'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnerinfo',
            name='Email',
            field=models.EmailField(default=1, max_length=90),
            preserve_default=False,
        ),
    ]
