# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_returnerinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlost',
            name='item_picture',
            field=models.ImageField(default=1, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
