# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20180115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlost',
            name='item_picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
