# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20180116_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemlost',
            old_name='item_picture',
            new_name='image',
        ),
    ]
