# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20180117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlost',
            name='image',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
